agent:
  labels: {}
  # W&B API key.
  apiKey: ""
  # Container image to use for the agent.
  image: wandb/launch-agent-dev:latest
  # Image pull policy for agent image.
  imagePullPolicy: Always
  # Resources block for the agent spec.
  resources:
    requests:
      cpu: 4
      memory: 16Gi
    limits:
      cpu: 4
      memory: 16Gi
  # Node selector for the agent pod.
  nodeSelector: {}
  # Job start timeout (seconds)
  startTimeout: 1800

# Region to launch in CW [ORD1, LAS1, LGA1]
region: ORD1

# W&B api url (Set yours here)
baseUrl: https://api.wandb.ai

# This should be set to the literal contents of your launch agent config.
launchConfig: |
  queues:  # List of queues to poll for jobs.
  - <YOUR QUEUE NAME>
  max_jobs: 10  # Max number of jobs to run concurrently.
  max_schedulers: 1  # Max number of sweep schedulers to run concurrently.
  builder:  # Builder config. Type `noop` and `kaniko` can be used in a kubernetes cluster.
    type: noop


