---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wandb-launch-serviceaccount
  namespace: {{ .Release.Namespace }}
{{- if .Values.serviceAccount.annotations }}
  annotations:
{{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
{{- if eq "user" .Values.scope }}
kind: Role
{{ else if eq "cluster" .Values.scope}}
kind: ClusterRole
{{ end }}
metadata:
  namespace: {{ .Release.Namespace }}
  name: wandb-launch-agent
rules:
  - apiGroups: [""]
    resources: ["pods", "configmaps", "secrets", "pods/log"]
    verbs: ["create", "get", "watch", "list", "update", "delete", "patch"]
  - apiGroups: ["batch"]
    resources: ["jobs", "jobs/status"]
    verbs: ["create", "get", "watch", "list", "update", "delete", "patch"]
...
---
apiVersion: rbac.authorization.k8s.io/v1
{{- if eq "user" .Values.scope }}
kind: Role
{{ else if eq "cluster" .Values.scope}}
kind: ClusterRole
{{ end }}
metadata:
  name: job-creator
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "secrets"]
    verbs: ["create", "get", "watch", "list", "update", "delete", "patch"]
  - apiGroups: ["batch"]
    resources: ["jobs", "jobs/status"]
    verbs: ["create", "get", "watch", "list", "update", "delete", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wandb-launch-role-binding
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: wandb-launch-serviceaccount
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: wandb-launch-agent
  apiGroup: rbac.authorization.k8s.io
...
{{- define "unique.namespaces" }}
{{- $root := . -}}
{{- $unique := uniq (append .Values.additionalTargetNamespaces .Values.namespace) }}
{{- range $ns := $unique }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wandb-launch-cluster-role-binding
  namespace: {{ $ns }}
subjects:
  - kind: ServiceAccount
    name: wandb-launch-serviceaccount
    namespace: {{ $root.Values.namespace }}
roleRef:
  kind: Role
  name: job-creator
  apiGroup: rbac.authorization.k8s.io
...
{{- end }}
{{- end }}

